### ISSUE TITLE
FTR: Gather requirements for a Vega leaderboard

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/community#22]
A leaderboard that displays trader and liquidity provider rankings. So much we could do, so let's collect requirements and spin up a developer bounty for it!

**Comment by zachit** [comment]
I've spoken with my friend who made https://getwoke.me/ and he's open to help with making it work for Vega. This would just be for linking a leaderboard to twitter accounts.

**Comment by cdm** [comment]
Great to see us rebooting leaderboards. We built a simple one a while ago, for me it'd be great to collect a list on the ticket of the data points we'd like to display in the _Leaderboard_ 

That'd help me prep/advise on the query or any extra work needed to make this bounty possible. I've got a simple polling API service that we used last time to provide 'realtime' quote updates for values on the settlement asset value in USD etc.

**Comment by cdm** [comment]
I'd love to get some traction with this, will set up some time to discuss with the community core group. If the team has examples of other projects leaderboards or CEX leaderboards that could work well for us please link them in this thread 📣 

@zachit thank you the more collaborative the better 💪

**Comment by daunjuan** [comment]
I think looking at Bitmax can give an idea of something people are used to, however it is a bit boring.
To keep it lively I would suggest daily winners and overall. 
https://www.bitmex.com/app/leaderboard
To keep activity up perhaps something that makes them trade daily requirement as well?

**Comment by daunjuan** [comment]
Would be nice to have similar what e.g. google does when you search for premier league table, where you can see the past few games/trades red, green etc
As well as fifa with ranking going up or down, but might get messy.
However, a rank name I really thing is interesting, like grand master etc, make it more game like, like starcraft and they do.
@cdm 
<img width="1355" alt="Screenshot 2021-02-25 at 20 55 42" src="https://user-images.githubusercontent.com/70202527/109209673-18daba00-77ac-11eb-8262-0be7467b27bc.png">
<img width="1279" alt="Screenshot 2021-02-25 at 20 53 23" src="https://user-images.githubusercontent.com/70202527/109209686-2001c800-77ac-11eb-851a-59e14d40b600.png">
<img width="674" alt="Screenshot 2021-02-25 at 20 52 47" src="https://user-images.githubusercontent.com/70202527/109209689-209a5e80-77ac-11eb-9171-0b06961cfbd5.png">

**Comment by zachit** [comment]
The BitMex leaderboards are fun. Top by notional and ROE. Being able to add a handle to recognise your wallet on the leaderboard would be great functionality. 

Integrating twitter would be great of course, but fine with just names to begin with. My friend with the twitter project is way too overloaded at the moment unfortunately. Axelar are trying to get their testnet out. The twitter integration we could do pretty simply with just a signed tx from their wallet, posted to twitter?

You could include an orders per block or per day. This could be fun for bot builders, and be a sly incentive for trying to break Vega with lots of orders.

**Comment by zachit** [comment]
Should expose volume too, of course. FTX has maker volume, maker/total volume ratio would be interesting too, but not sure if something for a leaderboard.

**Comment by campbellssource** [comment]
I think competitions could be: 
Profit based:
- **Single asset**. Increase the amount of an asset you have at the end of the day, comparing amount Fauceted/given Vs amount at end of day
- **Single market** Who has the biggest profit on a given market. (some sort of adjustment given that one can Faucet, or with finite asset)
- **Portfolio** as above but where all assets are converted into a single compatible currency. This is harder.

Competitions could also be event or activity based: e.g.
- number of transactions
- number of close outs initiated by combatant
- first to hit margin release zone 
- collected maker fees
- collected liquidity fees
- ad infinitum 

In the sprit of agile iteration I'm tempted to suggest:
**First**: a board where you select an asset and then see how people rank by comparing amount given/deposited Vs current. (perhaps with sub grouping for "available", "deployed", in "liquidity bond" and not including "to withdraw")

Each competition will need its own Asset (and consequently market). (unless we add a time range to the comparison 🤯 ( I don't suggest we do that)

**Second**: a single market leader board is also relatively easy but I haven't figured out how you make it fair when assets can be Fauceted

Now we can introduce a mode to the board, market mode you select the market asset mode you select the asset.

**Third**: a leader board that can simply sort parties by a single field or thing you can point at in the block explorer

**then more** when we get there

**Comment by campbellssource** [comment]
Or more generally we could have a service that takes a set of data and a formula that ranks the users. Forgive the pseudo code.

```
combatants = arrayofVegaKeysFromRegistrants
competitionStart
competitionEnd
//What the leaderboard needs to fetch
competitionData = (
  startBal = sumOfAllDeposits since competitionStart, 
  endBal = availableBalance.tBTC OR availableBalance.tBTC at competitionEnd
)
//How it ranks people
competitionRank = (
  endBal / startBal * 100
)
Foreach($combatant in $combatants){
  fetch combatant.competitionData 
}
Sort combatants by competitionRank
```

**Comment by campbellssource** [comment]
just seen https://github.com/vegaprotocol/priceproxy So perhaps the portfolio methods would be doable if all assets in the competitions exist elsewhere in the world

**Comment by cdm** [comment]
We're nearly completing some exciting work in this area internally, thank you all for your feedback and input - it's been invaluable 🥳
