### ISSUE TITLE
FTR: Website copy - specifics of the games

### ISSUE THREAD

**Issue by tamlyn10** [vegaprotocol/community#32]

**Comment by campbellssource** [comment]
There is now a pro forma tab at the bottom of a previous spreadsheet https://docs.google.com/spreadsheets/d/1elpOlJjSEi7dtmdEj5WGb47uvbByYXOA5YuI9ffh7K8/edit#gid=1666207224

**Comment by campbellssource** [comment]
and a potential duplicate ticket: https://github.com/vegaprotocol/community/issues/10
